name: Deploy to Salesforce

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    name: Deploy to Salesforce
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global


      - name: Authenticate with Salesforce
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} \
          --jwtkeyfile assets/server.key --username ${{ secrets.SF_USERNAME }} \
          --instanceurl https://login.salesforce.com
        env:
          SFDX_ENV: production
          
      # Deploy su Salesforce
      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app --checkonly --wait 10
          sfdx force:source:deploy -p force-app --testlevel RunLocalTests
