name: Deploy to Salesforce

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    name: Deploy to Salesforce
    runs-on: ubuntu-latest

    steps:
        - name: Checkout del repository
          uses: actions/checkout@v3

        - name: Install Salesforce CLI
          run: |
            sudo npm install --global sfdx-cli

        - name: Autenticazione con Salesforce
          run: |
            echo "${{ secrets.SF_USERNAME }}" > username.txt
            echo "${{ secrets.SF_PASSWORD }}" > password.txt
            echo "${{ secrets.SF_SECURITY_TOKEN }}" > token.txt
            sf org login web --username "$(cat username.txt)" --password "$(cat password.txt)$(cat token.txt)"

          env:
            SF_USERNAME: ${{ secrets.SF_USERNAME }}
            SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
            SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}

        - name: Deploy su Salesforce
          run: |
            sfdx force:source:deploy -p force-app/main/default