name: Salesforce Deploy

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Installazione CLI
      run: |
        npm install -g sfdx-cli 

    - name: Salesforce Login via JWT
      run: |
        echo "${{ secrets.SF_PRIVATE_KEY }}" | sfdx force:auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile /dev/stdin --username ${{ secrets.SF_USERNAME }} --setdefaultdevhubusername --alias my-hub-org

    - name: Salesforce Deploy
      run: |
        sfdx force:source:deploy -x manifest/package.xml -u my-hub-org