name: Salesforce CLI Workflow

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest  # or windows-latest if you're on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out your repository

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the version of Node.js

    - name: Install Salesforce CLI
      run: |
        curl -sL https://sfdx-cli.herokuapp.com/install.sh | bash
        echo "Salesforce CLI installed successfully."

    - name: Add CLI to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_ENV  # Ensure the installation path is in the PATH
  
    - name: Verify Salesforce CLI Installation
      run: |
        echo "PATH: $PATH"  # Print the current PATH to debug
        sf --version  # Check if the Salesforce CLI is installed

    - name: Create credential files
      run: |
        echo "${{ secrets.SF_USERNAME }}" > username.txt
        echo "${{ secrets.SF_PASSWORD }}" > password.txt
        echo "${{ secrets.SF_SECURITY_TOKEN }}" > token.txt

    - name: Login to Salesforce
      run: |
        sf org login web --username "$(cat username.txt)" --password "$(cat password.txt)$(cat token.txt)" --setalias MyOrg --setdefaultusername


    - name: Deploy su Salesforce
      run: |
        sfdx force:source:deploy -p force-app/main/default