name: Salesforce Deploy

on:
  pull_request:
    types: [opened, synchronize]  # Trigger sul merge (pull request chiusa)
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Installazione CLI
      run: |
        npm install -g @salesforce/cli 

    - name: Salesforce Login via JWT
      run: |
        echo "${{ secrets.SF_PRIVATE_KEY }}" | sf auth:jwt:grant --client-id ${{ secrets.SF_CLIENT_ID }} --jwt-key-file /dev/stdin --username ${{ secrets.SF_USERNAME }} --set-default-dev-hub --alias my-hub-org

    - name: Salesforce Deploy
      run: |
        sf project deploy start --manifest manifest/package.xml --target-org my-hub-org
