name: Salesforce Deploy

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Installazione CLI
      run: |
        npm install -g @salesforce/cli

    - name: Debug Segreti
      run: |
        echo "Client ID: ${{ secrets.SF_CLIENT_ID }}"
        echo "Username: ${{ secrets.SF_USERNAME }}"
        echo "Chiave privata lunghezza: $(echo "${{ secrets.SF_PRIVATE_KEY }}" | wc -c)"
        echo "Controllo chiave privata (prime 5 righe):"
        echo "${{ secrets.SF_PRIVATE_KEY }}" | head -n 5

    - name: Creare e Usare File Temporaneo per la Chiave Privata
      run: |
        printf "%s" "${{ secrets.SF_PRIVATE_KEY }}" > private_key.pem
        sf auth jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile private_key.pem --username ${{ secrets.SF_USERNAME }} --setdefaultdevhubusername --alias my-hub-org
        rm private_key.pem

    - name: Salesforce Deploy
      run: |
        sf deploy source -x manifest/package.xml -u my-hub-org

