name: Salesforce Deploy

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Installazione CLI
      run: |
        npm install -g @salesforce/cli

    - name: Creare e Usare File Temporaneo per la Chiave Privata
      run: |
        # Creare file temporaneo per la chiave privata
        echo "${{ secrets.SF_PRIVATE_KEY }}" > private_key.pem
        # Usare il file per autenticazione
        sf auth jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile private_key.pem --username ${{ secrets.SF_USERNAME }} --setdefaultdevhubusername --alias my-hub-org
        # Rimuovere il file temporaneo
        rm private_key.pem

    - name: Salesforce Deploy
      run: |
        sf deploy source -x manifest/package.xml -u my-hub-org

