name: Salesforce Deploy

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Installazione CLI
      run: |
        npm install -g sfdx-cli 

    - name: Creazione file chiave privata
      run: |
        echo "${{ secrets.SF_PRIVATE_KEY }}" > server.key

    - name: Salesforce Login via JWT
      run: |
        sfdx auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} \
                            --jwtkeyfile server.key \
                            --username ${{ secrets.SF_USERNAME }} \
                            --instanceurl https://login.salesforce.com \
                            --setdefaultdevhubusername

    - name: Salesforce Deploy
      run: |
        sfdx force:source:deploy -p force-app/main/default
