name: Deploy to Salesforce

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    name: Deploy to Salesforce
    runs-on: ubuntu-latest

    steps:
        - name: Checkout del repository
          uses: actions/checkout@v3

        - name: Install Salesforce CLI
          run: |
            sudo npm install --global sfdx-cli

        - name: Autenticazione con Salesforce
          run: |
            sf org login web --username ${{ secrets.SF_USERNAME }} --password ${{ secrets.SF_PASSWORD }} --instance-url https://login.salesforce.com
  
        - name: Deploy su Salesforce
          run: |
            sfdx force:source:deploy -p force-app/main/default